home/urls.py
from django.urls import path, include

from home import views

urlpatterns = [
    path("", views.index, name='home'),

]

product/urls.py
from django.urls import path

from product import views

urlpatterns = [
    path("category/", views.all_categories, name='category.all'),
    path("category/<int:pk>/products", views.category_products, name='category.products'),
    path("seller/", views.all_sellers, name='seller.all'),
    path("seller/discount", views.seller_discount, name='seller.discount'),
    path("seller/<int:pk>/add_payment", views.add_seller_payment, name='seller.add_payment'),
    path("seller/remote_invoices", views.remote_seller_invoices, name='seller.remote_invoices'),
    path("seller/remote_payments", views.remote_seller_payments, name='seller.remote_payments'),
    path("worker/", views.all_workers, name='worker.all'),
    path("box/", views.daily_box, name='box.daily'),
    path("quantity_types/", views.all_quantity_types, name='quantity_type.all'),
    path("currency/", views.all_currencies, name='currency.all'),
    path("material/", views.all_materials, name='material.all'),
    path("invoice/add", views.add_invoice, name='invoice.add'),
    path("payment/all", views.all_payments, name='payment.all'),
    path("invoice/<int:pk>/", views.view_invoice, name='invoice.view'),
    path("invoice/return", views.returned_invoices, name='invoice.returned'),
    path("invoice/<int:pk>/return", views.return_invoice, name='invoice.return'),
    path("invoice/<int:pk>/edit", views.edit_invoice, name='invoice.edit'),
    path("invoice/seller/<int:pk>/", views.seller_invoices, name='invoice.seller.view'),
    path("invoice/last", views.view_invoice_last, name='invoice.view.last'),
    path("invoice/all", views.all_invoices, name='invoice.all'),
    path("product/add/", views.add_product, name='product.add'),
    path("product/offer/", views.offer, name='product.offer'),
    path("product/all_json/", views.get_all_products, name='product.all_json'),
    path("product/all_materials/", views.get_all_materials, name='product.all_materials'),
    path("product/<int:pk>/edit", views.edit_product, name='product.edit'),
    path("product/autocomplete/", views.product_autocomplete, name='product.autocomplete'),
    path("product/get_currencies/", views.get_currencies, name='product.get_currencies'),
    path("product/get_sellers/", views.get_sellers, name='product.get_sellers'),
    path("product/get_workers/", views.get_workers, name='product.get_workers'),
    path("product/report/<int:pk>/", views.product_report, name='product.report'),
    path("product/get_invoice_products/<int:pk>", views.get_invoice_products, name='product.get_invoice_products'),
    path("product/get_quantity_types/", views.get_quantity_types, name='product.get_quantity_types'),
    path("", views.all_products, name='product.all'),
    path("rawad/", views.rawad, name='product.rawad'),
    path("show/", views.show, name='product.show'),
    path("reports/", views.all_reports, name='reports.all'),
    path("exports/", views.all_exports, name='all_exports'),
]

turbo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include("product.urls")),
                  path('users/', include("users.urls")),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                                           document_root=settings.MEDIA_ROOT)

product/models.py
from django.db import models
from model_utils import Choices


class Material(models.Model):
    name = models.CharField(max_length=100, unique=True)
    desc = models.CharField(max_length=200, null=True, blank=False)

    def __str__(self):
        return self.name


class QuantityType(models.Model):
    name = models.CharField(max_length=100, unique=True)
    value = models.FloatField()

    def __str__(self):
        return self.name


class Currency(models.Model):
    name = models.CharField(max_length=100, unique=True)
    value = models.FloatField()
    rate = models.FloatField()

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    desc = models.CharField(max_length=200, null=True, blank=False, default=None)
    TYPE = Choices('Super', 'Regular')
    type = models.CharField(max_length=100, choices=TYPE, default=TYPE.Regular)

    def __str__(self):
        return self.name


class Seller(models.Model):
    name = models.CharField(max_length=100, unique=True)
    phone = models.CharField(max_length=200, null=True, unique=True, blank=False)
    address = models.CharField(max_length=200, null=True, blank=False)
    old_account = models.FloatField(default=0, blank=True)

    def __str__(self):
        return self.name


class Worker(models.Model):
    name = models.CharField(max_length=100, unique=True)
    phone = models.CharField(max_length=200, null=True, unique=True, blank=False)

    def __str__(self):
        return self.name


class Product(models.Model):
    STATUS = Choices('KG', 'Liter')
    name = models.CharField(max_length=100, unique=True)
    stock_price = models.FloatField()
    price = models.FloatField()
    special = models.FloatField()
    expire = models.DateField(null=True, blank=False)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    seller = models.ForeignKey(Seller, on_delete=models.SET_NULL, null=True)
    material = models.ManyToManyField(Material)
    quantity_type = models.ForeignKey(QuantityType, on_delete=models.SET_NULL, null=True)
    quantity = models.FloatField()
    weight = models.CharField(max_length=100, choices=STATUS, default=STATUS.KG)
    weight_value = models.FloatField(default=0)
    extra_quantity = models.FloatField(null=True, default=0)
    barcode = models.CharField(null=True, max_length=100, blank=False, default=" ")
    identifier = models.CharField(null=True, max_length=100, blank=False)
    # Abbrivation = models.CharField(null=True, max_length=10, blank=False)
    location = models.CharField(null=True, max_length=100, blank=False)
    alert_if_lower_than = models.IntegerField(null=True)
    image = models.CharField(max_length=100, blank=False, null=True)

    def __str__(self):
        return self.name


class Invoice(models.Model):
    TYPE = Choices('Sale', 'Purchase', 'Return')
    OLD_TYPE = Choices('Sale', 'Purchase')
    type = models.CharField(max_length=100, choices=TYPE, default=TYPE.Sale)
    old_type = models.CharField(max_length=100, choices=OLD_TYPE, default='Sale')
    discount = models.FloatField(default=0)
    discount_reason = models.CharField(max_length=300, default=" ")
    earn = models.FloatField(blank=True, null=True, default=0)
    total = models.FloatField()
    date_added = models.DateTimeField(auto_now_add=True)
    seller = models.ForeignKey(Seller, on_delete=models.SET_NULL, null=True)
    worker = models.ForeignKey(Worker, on_delete=models.SET_NULL, null=True)
    image = models.CharField(max_length=100, blank=False, null=True)


class InvoiceProduct(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, )
    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE, )
    quantity = models.FloatField()
    extra_quantity = models.FloatField()
    quantity_type = models.ForeignKey(QuantityType, on_delete=models.CASCADE, )
    piece_price = models.FloatField()
    total = models.FloatField()
    total_pices = models.FloatField(default=0)
    total_pices_count = models.FloatField(default=0)


class InvoicePayment(models.Model):
    seller = models.ForeignKey(Seller, on_delete=models.CASCADE, )
    currency = models.ForeignKey(Currency, on_delete=models.CASCADE, )
    add_date = models.DateTimeField(auto_now_add=True)
    rate = models.FloatField(default=1)
    amount = models.FloatField()
    OPERATIONS = Choices('Give', 'Take')
    operation = models.CharField(choices=OPERATIONS, max_length=5, default=OPERATIONS.Give)
    image = models.CharField(max_length=100, blank=False, null=True)


class DailyBoxOperation(models.Model):
    OPERATIONS = Choices('Give', 'Take')
    currency = models.ForeignKey(Currency, on_delete=models.CASCADE, )
    amount = models.FloatField()
    operation = models.CharField(choices=OPERATIONS, max_length=5, default=OPERATIONS.Give)
    reason = models.CharField(max_length=255)
    add_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)


class SellerDiscount(models.Model):
    seller = models.ForeignKey(Seller, on_delete=models.CASCADE, )
    amount = models.FloatField()
    add_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)

product/forms.py
from django import forms
from django.forms import ModelForm, HiddenInput

from product.models import *


class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = "__all__"


class SellerForm(ModelForm):
    class Meta:
        model = Seller
        fields = "__all__"

    # def __init__(self, *args, **kwargs):
    #     super(SellerForm, self).__init__(*args, **kwargs)
    #     # super().__init__()
    #     # self.fields['old_account'].widget = HiddenInput()


class InvoicePaymentForm(ModelForm):
    class Meta:
        model = InvoicePayment
        fields = "__all__"


class DailyBoxOperationForm(ModelForm):
    class Meta:
        model = DailyBoxOperation
        fields = "__all__"


class WorkerForm(ModelForm):
    class Meta:
        model = Worker
        fields = "__all__"


class CurrencyForm(ModelForm):
    class Meta:
        model = Currency
        fields = "__all__"


class QuantityTypeForm(ModelForm):
    class Meta:
        model = QuantityType
        fields = "__all__"


class MaterialForm(ModelForm):
    class Meta:
        model = Material
        fields = "__all__"


class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = "__all__"


class InvoiceForm(ModelForm):
    class Meta:
        model = Invoice
        fields = ["discount", "discount_reason", "image"]


class SellerDiscountForm(ModelForm):
    class Meta:
        model = SellerDiscount
        fields = ["amount", "seller"]

templates/product/add.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="card">
        <div class="card-header d-flex justify-content-between align-items-center">
            <span>
                Add New Product
            </span>

            <a class="link" href="{% url 'product.all' %}">All Products</a>
        </div>
        <div class="card-body">
            <form method="post" action="{% url 'product.add' %}">
                {% csrf_token %}
                <div class="row">
                    {#General#}
                    <div class="col-12 col-md-6 mb-4">
                        <div class="card">
                            <div class="card-header">General information</div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-12 col-md-6">{{ form.name|as_crispy_field }}</div>
                                    <div class="col-12 col-md-6">{{ form.location|as_crispy_field }}</div>
                                    <div class="col-12 col-md-6">{{ form.identifier|as_crispy_field }}</div>
                                    <div class="col-12 col-md-6">{{ form.barcode|as_crispy_field }}</div>
                                    <div class="col-12 col-md-6">{{ form.weight|as_crispy_field }}</div>
                                    <div class="col-12 col-md-6">{{ form.weight_value|as_crispy_field }}</div>
                                    <div class="col-12 col-md-6">
                                        {{ form.expire|as_crispy_field }}

                                    </div>
                                    <div class="col-12 col-md-6">
                                        <div style="display:none;">
                                            {{ form.image|as_crispy_field }}
                                        </div>
                                        <label for="formFile" class="form-label">Image</label>
                                        <input class="form-control" type="file" id="image">
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                    {# Pricing #}
                    <div class="col-12 col-md-6 mb-4">
                        <div class="card">
                            <div class="card-header">Pricing ($)</div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-12 col-md-6">{{ form.stock_price|as_crispy_field }}</div>
                                    <div class="col-12 col-md-6">{{ form.price|as_crispy_field }}</div>
                                    <div class="col-12 col-md-6">{{ form.special|as_crispy_field }}</div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {# Relations #}
                    <div class="col-12 col-md-6 mb-4">
                        <div class="card">
                            <div class="card-header">Relations</div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-12 col-md-6">{{ form.category|as_crispy_field }}</div>
                                    <div class="col-12 col-md-6">{{ form.seller|as_crispy_field }}</div>
                                    <div class="col-12 col-md-6">{{ form.material|as_crispy_field }}</div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {# Quantity #}
                    <div class="col-12 col-md-6 mb-4">
                        <div class="card">
                            <div class="card-header">Quantity</div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-12 col-md-6">{{ form.quantity_type|as_crispy_field }}</div>
                                    <div class="col-12 col-md-6">{{ form.quantity|as_crispy_field }}</div>
                                    <div class="col-12 col-md-6">{{ form.extra_quantity|as_crispy_field }}</div>
                                    <div class="col-12 col-md-6">{{ form.alert_if_lower_than|as_crispy_field }}</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-success">Add Product</button>
            </form>
        </div>
    </div>

    <style>
        .v-application--wrap {
            min-height: unset;
        }
    </style>

    <script>
        $('document').ready(function () {
            $('#image').on('change', function () {
                var $files = $(this).get(0).files;

                if ($files.length) {
                    // Reject big files
                    if ($files[0].size > $(this).data('max-size') * 1024) {
                        console.log('Please select a smaller file');
                        return false;
                    }
                    console.log('Uploading file to Imgur..');
                    var apiUrl = 'https://api.imgur.com/3/image';
                    var apiKey = 'ee1ec982b2a8cb9';
                    var settings = {
                        async: false,
                        crossDomain: true,
                        processData: false,
                        contentType: false,
                        type: 'POST',
                        url: apiUrl,
                        headers: {
                            Authorization: 'Client-ID ' + apiKey,
                            Accept: 'application/json',
                        },
                        mimeType: 'multipart/form-data',
                    };

                    var formData = new FormData();
                    formData.append('image', $files[0]);
                    settings.data = formData;
                    $.ajax(settings).done(function (response) {
                        $("#id_image").val(JSON.parse(response).data["link"])
                        alert("Image uploaded successfully")
                    });
                }
            });
        });
    </script>
{% endblock %}

templates/product/edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="card">
        <div class="card-header d-flex justify-content-between align-items-center">
            <span>
                Add New Product
            </span>

            <a class="link" href="{% url 'product.all' %}">All Products</a>
        </div>
        <div class="card-body">
            <form method="post" action="{% url 'product.edit' product.pk %}">
                {% csrf_token %}
                <div class="row">
                    {#General#}
                    <div class="col-12 col-md-6 mb-4">
                        <div class="card">
                            <div class="card-header">General information</div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-12 col-md-6">{{ form.name|as_crispy_field }}</div>
                                    <div class="col-12 col-md-6">{{ form.location|as_crispy_field }}</div>
                                    <div class="col-12 col-md-6">{{ form.identifier|as_crispy_field }}</div>
                                    <div class="col-12 col-md-6">{{ form.barcode|as_crispy_field }}</div>
                                    <div class="col-12 col-md-6">{{ form.weight|as_crispy_field }}</div>
                                    <div class="col-12 col-md-6">{{ form.weight_value|as_crispy_field }}</div>
                                    <div class="col-12 col-md-6">
                                        {{ form.expire|as_crispy_field }}
                                    </div>
                                    <div class="col-12 col-md-6">
                                        <div style="display:none;">
                                            {{ form.image|as_crispy_field }}
                                        </div>
                                        <label for="formFile" class="form-label">Image</label>
                                        <input class="form-control" type="file" id="image">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {# Pricing #}
                    <div class="col-12 col-md-6 mb-4">
                        <div class="card">
                            <div class="card-header">Pricing ($)</div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-12 col-md-6">{{ form.stock_price|as_crispy_field }}</div>
                                    <div class="col-12 col-md-6">{{ form.price|as_crispy_field }}</div>
                                    <div class="col-12 col-md-6">{{ form.special|as_crispy_field }}</div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {# Relations #}
                    <div class="col-12 col-md-6 mb-4">
                        <div class="card">
                            <div class="card-header">Relations</div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-12 col-md-6">{{ form.category|as_crispy_field }}</div>
                                    <div class="col-12 col-md-6">{{ form.seller|as_crispy_field }}</div>
                                    <div class="col-12 col-md-6">{{ form.material|as_crispy_field }}</div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {# Quantity #}
                    <div class="col-12 col-md-6 mb-4">
                        <div class="card">
                            <div class="card-header">Quantity</div>
                            <div class="card-body">
                                <div class="row">
{#                                    <div class="col-12 col-md-6">{{ form.quantity_type|as_crispy_field }}</div>#}
{#                                    <div class="col-12 col-md-6">{{ form.quantity|as_crispy_field }}</div>#}
{#                                    <div class="col-12 col-md-6">{{ form.extra_quantity|as_crispy_field }}</div>#}
                                    <div class="col-12 col-md-6">{{ form.alert_if_lower_than|as_crispy_field }}</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-success">Update Product</button>
            </form>
        </div>
    </div>

    <style>
        .v-application--wrap {
            min-height: unset;
        }
    </style>
    <script>
        var app = new Vue({
            delimiters: ["[[", "]]"],
            el: '#dpick',
            vuetify: new Vuetify(),
            data: () => {
                return {
                    exp: new Date().toISOString().split("T")[0],
                    menu1: false
                }
            }
        })
    </script>

    <script>
        $('document').ready(function () {
            $('#image').on('change', function () {
                var $files = $(this).get(0).files;

                if ($files.length) {
                    // Reject big files
                    if ($files[0].size > $(this).data('max-size') * 1024) {
                        console.log('Please select a smaller file');
                        return false;
                    }
                    console.log('Uploading file to Imgur..');
                    var apiUrl = 'https://api.imgur.com/3/image';
                    var apiKey = 'ee1ec982b2a8cb9';
                    var settings = {
                        async: false,
                        crossDomain: true,
                        processData: false,
                        contentType: false,
                        type: 'POST',
                        url: apiUrl,
                        headers: {
                            Authorization: 'Client-ID ' + apiKey,
                            Accept: 'application/json',
                        },
                        mimeType: 'multipart/form-data',
                    };

                    var formData = new FormData();
                    formData.append('image', $files[0]);
                    settings.data = formData;
                    $.ajax(settings).done(function (response) {
                        $("#id_image").val(JSON.parse(response).data["link"])
                        alert("Image uploaded successfully")
                    });
                }
            });
        });
    </script>
{% endblock %}

templates/product/product_report.html
{% extends "base.html" %}
{% block content %}
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    Selled (<span id="total" style="font-weight: bold"></span>)
                    <span> / Grand Saled quantity  (<span id="gr"></span>) </span>
                </div>
                <div class="card-body">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>Seller</th>
                            <th>Quantity</th>
                            <th>Extra Quantity</th>
                            <th>Piece Price From Stock</th>
                            <th>Piece Price Sale</th>
                            <th>Earned</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for invoice in si %}
                            <tr>
                                <td>{{ invoice.seller }}</td>
                                {% for product in invoice.invoiceproduct_set.all %}
                                    {% if product.product.pk == bproduct.id %}
                                        <td>{{ product.quantity }}</td>
                                        <td>{{ product.extra_quantity }}</td>
                                        <td>{{ bproduct.stock_price }}</td>
                                        <td>{{ product.piece_price }}</td>
                                        <td class="earn" stock-price="{{ bproduct.price }}"
                                            piece-price="{{ product.piece_price }}"
                                            extra-quantity="{{ product.extra_quantity }}"
                                            quantity="{{ product.quantity }}"
                                            quantity-type-value="{{ bproduct.quantity_type.value }}">

                                        </td>
                                    {% endif %}
                                {% endfor %}
                            </tr>

                        {% endfor %}

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    Purchased
                </div>
                <div class="card-body">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>Seller</th>
                            <th>Piece Price</th>
                            <th>Total</th>
                            <th>Quantity</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for invoice in pi %}
                            <tr>
                                <td>{{ invoice.seller }}</td>
                                {% for product in invoice.invoiceproduct_set.all %}
                                    {% if product.product.pk == bproduct.id %}
                                        <td>{{ product.piece_price }}</td>
                                        <td>{% widthratio product.piece_price 1 product.quantity %}</td>
                                        <td>{{ product.quantity }}</td>
                                    {% endif %}
                                {% endfor %}
                            </tr>

                        {% endfor %}

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <script>
        $(document).ready(function () {
            let total = 0
            let totalQuantity = 0
            $.each($(".earn"), function () {
                let stock_price = parseFloat($(this).attr("stock-price"))
                let piece_price = parseFloat($(this).attr("piece-price"))
                let extra_quantity = parseFloat($(this).attr("extra-quantity"))
                let quantity = parseFloat($(this).attr("quantity"))
                let quantity_type_value = parseFloat($(this).attr("quantity-type-value"))
                {#    #}
                let totalPieceQuantity = (quantity * quantity_type_value) + extra_quantity
                let totalPriceFromStock = totalPieceQuantity * stock_price
                let totalPriceFromSale = totalPieceQuantity * piece_price
                let earn = totalPriceFromStock - totalPriceFromSale
                $(this).text(earn + "$")

                total += earn
                totalQuantity += (totalPieceQuantity / quantity_type_value)
            })
            $("#total").text(total + '$')
            $("#gr").text(totalQuantity)
        })
    </script>
{% endblock %}

templates/product/show.html
{% extends "base.html" %}
{% block content %}
    <div class="row">
        {% for product in products %}
            <div class="col-md-3">
                <div class="px-1">
                    <div class="bg-light rounded">
                        <div class="p-2">
                            <img src="{{ product.image }}" alt="" class="img-fluid rounded">
                            <h5 class="pt-3 pb-2 text-capitalize">{{ product.name }}</h5>
{#                            <h3>{{ product.price }}$</h3>#}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}